name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: actions/setup-node@v2
      with:
        node-version: '17'
    - name: Install dependencies and grammar
      run: npm install
